# Cyber Punk Neon
# Source https//github.com/Roboron3042/Cyberpunk-Neon

    #  bg = "#16181a",
    # bgAlt = "#1e2124",
    # bgHighlight = "#3c4048",
    # fg = "#ffffff",
    # grey = "#7b8496",
    # blue = "#5ea1ff",
    # green = "#5eff6c",
    # cyan = "#5ef1ff",
    # red = "#ff6e5e",
    # yellow = "#f1ff5e",
    # magenta = "#ff5ef1",
    # pink = "#ff5ea0",
    # orange = "#ffbd5e",
    # purple = "#bd5eff",

# Default colors
[colors.primary]
background = '#000b1e'
foreground = '#ffffff'

[colors.cursor]
text   = '#000b1e'
cursor = '#0abdc6'

# Normal colors
[colors.normal]
black   = '#123e7c'
red     = '#ff315e'
green   = '#5eff6c'
yellow  = '#ffbd5e'
blue    = '#5ea1ff'
magenta = '#ff5ef1'
cyan    = '#5ef1ff'
white   = '#ffffff'

